extract_document_sections_task:
  description: >
    Read the scientific document and divide it into logical sections
    such as Introduction, Methods, Results and Discussion.
  expected_output: >
     A structured JSON or list of text segments representing each document section.
  agent: reader_agent
  # args:
  #     file_path: "documents/PlanetaTransparente.pdf"

summarize_sections_task:
  description: >
    Generate summaries for each of the extracted sections using the selected LLM,
    enriched with relevant context through RAG if necessary.
  expected_output: >
    A set of concise, well-structured summaries corresponding to each section of the document.
  agent: summarizer_agent
  # input_tasks:
  #   extract_document_sections

compile_final_summary_task:
  description: >
    Review and merge all section summaries into one cohesive document-level summary.
     Ensure clarity, consistency, and logical flow throughout the final output.
  expected_output: >
    A complete, well-organized final summary of the scientific document.
  agent: coordinator_agent
  # input_tasks:
  #   summarize_sections

